name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: 18.6.0
          registry-url: https://npm.pkg.github.com/
          scope: '@nourhankhalifa'
          
      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build library
        run: npm run build
        
      - name: Publish package
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${NPM_TOKEN}" >> .npmrc
          npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}